apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingestion-deploy.yaml
  - ingestion-service.yaml
  - ingestion-ingress.yaml

secretGenerator:
  - name: dataflow-ingestion-secrets
    envs:
      - .env
