import { BackstageTypography } from '@backstage/theme';
import { FONT_FAMILY_SANS } from './fonts';

export const vercelTypography: BackstageTypography = {
  fontFamily: FONT_FAMILY_SANS,
  htmlFontSize: 16,
  h1: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '2rem',
    fontWeight: 600,
    lineHeight: 1.25,
    letterSpacing: '-0.025em',
    marginBottom: 10,
    color: '#000000',
  },
  h2: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '1.5rem',
    fontWeight: 600,
    lineHeight: 1.3,
    letterSpacing: '-0.02em',
    marginBottom: 8,
    color: '#000000',
  },
  h3: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '1.25rem',
    fontWeight: 600,
    lineHeight: 1.35,
    letterSpacing: '-0.02em',
    marginBottom: 6,
    color: '#000000',
  },
  h4: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '1.125rem',
    fontWeight: 600,
    lineHeight: 1.4,
    letterSpacing: '-0.015em',
    marginBottom: 6,
    color: '#000000',
  },
  h5: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '1rem',
    fontWeight: 600,
    lineHeight: 1.45,
    letterSpacing: '-0.01em',
    marginBottom: 4,
    color: '#000000',
  },
  h6: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '0.875rem',
    fontWeight: 600,
    lineHeight: 1.5,
    letterSpacing: '-0.01em',
    marginBottom: 2,
    color: '#000000',
  },
  body1: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '0.875rem',
    lineHeight: 1.5,
    color: '#000000',
  },
  body2: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '0.8125rem',
    lineHeight: 1.5,
    color: '#666666',
  },
  button: {
    fontFamily: FONT_FAMILY_SANS,
    fontWeight: 500,
    fontSize: '0.875rem',
    textTransform: 'none',
  },
  caption: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '0.75rem',
    lineHeight: 1.4,
    color: '#888888',
  },
  overline: {
    fontFamily: FONT_FAMILY_SANS,
    fontSize: '0.6875rem',
    fontWeight: 600,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
} as unknown as BackstageTypography;
