apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingestion-deploy.yaml
  - ingestion-service.yaml
  - ingestion-ingress.yaml

configMapGenerator:
  - name: dataflow-ingestion-config
    files:
      - application.yaml=config/application.yaml

secretGenerator:
  - name: dataflow-ingestion-secrets
    envs:
      - .env
