spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataflow
    driverClassName: org.postgresql.Driver
    username: postgres-local
    password: postgres-local

  batch:
    jdbc:
      initialize-schema: always

---
db-scheduler:
  auto-create-tables: true

jobs:
  schedules:
    - name: customers-csv-ingest-job
      cron: "*/5 * * * * *"

  csv:
    - name: customers-csv-ingest-job
      source: http://localhost:8080/api/dummy/download
      token: none
      retryCount: 10
      retryInterval: 5000
      s3:
        endpoint: http://localhost:9000
        bucket: dataflow 
        access_key: minio-local
        secret_key: minio-local-password
        path_style_access: true
        region: us-east-1
      targetTable: customers
      copySql: classpath:sql/data/customers_csv_copy.sql
      insertSql: classpath:sql/data/customers_csv_insert.sql