app:
  rest:
    default:
      connectTimeout: 5000
      readTimeout: 5000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataflow
    driverClassName: org.postgresql.Driver
    username: postgres-local
    password: postgres-local
  sql:
    init:
      mode: alwqys
      schemaLocations:
        - classpath:sql/schema/db_scheduler.sql

db-scheduler-ui:
  history: true
  log:
    enabled: true
