spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataflow
    driverClassName: org.postgresql.Driver
    username: postgres-local
    password: postgres-local

db-scheduler-ui:
  history: true
  log:
    enabled: true
