logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dataflow
    driverClassName: org.postgresql.Driver
    username: postgres-local
    password: postgres-local
  sql:
    init:
      mode: always
      schemaLocations:
        - classpath:sql/schema/db_scheduler_sqlite.sql
  h2:
    console:
      enabled: true

---
app:
  s3:
    primary:
      endpoint: http://localhost:9000
      region: us-east-1 
      pathStyleAccess: true
      accessKey: minio-local
      secretKey: minio-local-password
  http: &http_clients
    deafult:
      logger-level: FULL
    dummy:
      url: http://localhost:8080
      # defaultRequestHeaders:
      #   Authorization: Basic xxxxxx

spring:
  cloud:
    openfeign:
      client:
        config: *http_clients

---
workflow:
  jobs:
    customers-csv-ingest-job:
      type: csv
      cron: 0 0 * * * *
      props:
        rest:
          clientId: dummy
          path: /customers-100.csv
        s3:
          clientId: primary
          bucket: dataflow 
          keyPattern: customers/v2/customers-{date}.csv
        postgres:
          tableName: customers_csv
          insertSql: classpath:sql/data/customers/customers_csv_insert.sql
          systemId: test
    
    departments-csv-ingest-job:
      type: csv
      cron: 0 0 * * * *
      props:
        rest:
          clientId: dummy
          path: /departments.csv
        s3:
          clientId: primary
          bucket: dataflow 
          keyPattern: customers/v2/departments-{date}.csv
        postgres:
          tableName: departments_csv
          insertSql: classpath:sql/data/customers/departments_csv_insert.sql
          systemId: test
